### ISSUE TITLE
mcmultipart{1.9-1.1.0} crashes client while connecting to server 

### ISSUE THREAD

**Issue by kreezxil** [amadornes/MCMultiPart#27]
client is using forge 1.9 build 1811

fml log http://paste.ee/p/KgtH5
crash http://paste.ee/p/HlxX2

**Comment by amadornes** [comment]
This is a known issue and just so you know _ALL_ the mods you have installed are going to have a very very similar crash until they all update because of a change in Forge. I fixed it on my end this morning and I'm waiting to see if the Forge team reverts the changes or if they stay this way. Once I know for sure, I'll push an update to Curse.
For now I'd suggest downgrading Forge to a version before 1805 (which if I recall correctly is when the change was introduced, if not you'll have to try yourself).
