### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Speiger** [amadornes/MCMultiPart#38]
Instead of making 2 TileEntity classes which are very limited to ticking TileEntities just make a differend system its way more modular & it can change very easy between none ticking & ticking.

Simply: Add a Shifted World Tick (using the WorldTickEvent) which asks then if the multipart ticks (adding a custom canUpdateFunction) if that is returned false it deletes it out of the TickingTileEntityList or adding it to it. With that you also can allow clientTileEntity Ticks and do not have to swtich TileEntityClasses...
(Which with my Experience causes only trouble)

**Comment by amadornes** [comment]
That's one of the options we considered when we started talking about ticking and non-ticking multiparts, but ended up discarding it because it would only cause issues and would be more annoying to work with. If we did it that way we'd have to make sure to remove all the parts in the block from the cache whenever `TileEntity#invalidate()` and `TileEntity#onChunkUnload()` are called, and add them back whenever `TileEntity#validate()` and `TileEntity#onLoad()` are called. Also, we'd be decoupling what are essentially TileEntity (multiparts can be considered a sort of TE) ticks from the world's tile ticking logic, rendering some mechanics like RFTools' "if the age isn't powered nothing ticks" completely useless for multipart tiles.

Another problem with what you're suggesting and that I've seen you suggest in other places is the fact that you're just trying to get around `ITickable`. It replaced `TileEntity#canTick()` for a reason, not just to annoy people, and in 99.99% of cases the change doesn't really affect how your mod's logic works. I understand that not having a `canTick()` method can be annoying, but that wasn't dynamic either. You still had to remove the TE and add it back (even if it wasn't a new one), so there isn't that big of a difference either.

After talking about it for a while, we saw that the 2-state 2-TE model was the best in terms of inter-mod compatibility, sticking to MC and Forge's way of doing things. Also, it works just fine so why go through all the hassle of changing it if it's only going to cause more trouble when it comes to things like moving the TileEntity around with frames and loading/unloading it?

**Comment by Speiger** [comment]
Well what you missunderstood here is that you think that the world tick event would replace the TileEntity tick. No the WorldTickEvent just processed shifted ticks that you say: i want you to make a tickCallback to validate that the TileEntity requires ticks. So you do not have to reset TileEntity classes everytime a new part got added. Also a canUpdate function / canTickFunction would allow a modular load of a tickingTileEntity. Whenever on reload a Multipart decides hey i need ticks it would not receive it simply because it does not check that at all and also your 2 TileEntity system does not support to have ClientSided indiviual Ticks outside of the Server Side.
Lets say a MultiPart has a animation that is having a Animation like a chest but server sided it requires no ticks then it would add a very small drag on the server doing nothing (while iterating through all components) and the client would receive its ticks. A can update function would allow you to say: Hey do you need ticks on this side? No ok then i remove myself out of the Ticking list if yes then i stay there.
Its way more modular then you think.
Also keep track of Ticking Multiparts and do not iterate through all parts blindless. Because that is just adding drag that is unnessesary...

And to point out your frame moving: Well if a Frame moves twice at 1 Tick (before onWorldPostTickEvent is called) then yes it could cause problems but then again: You can add in the callback a: IsTileEntityValid function, so you do not need to care about things like that...
