### ISSUE TITLE
Crash when using Placement Preview mod.

### ISSUE THREAD

**Issue by ChloeDawn** [amadornes/MCMultiPart#39]
Game crashes when looking at a MultiPart block such as a microblock from [Simple Covers](https://github.com/bdew/covers), and [Mekanism](https://github.com/aidancbrady/Mekanism) cables, whilst also using the [Placement Preview](https://github.com/maruohon/placementpreview) mod, which renders a preview of the block you're about to place. It crashes when trying to render the preview of the block.

To quote @maruohon: 

> "Seems that MCMultipart is not checking that the world is actually a WorldServer before trying to cast it to one."

**Full crash report:** [pastebin.com/CHEhbPYW](http://pastebin.com/CHEhbPYW)

Placement Preview version: [0.1.0](https://github.com/maruohon/placementpreview)
Minecraft version: 1.10.2
Forge version: [12.18.1.2046](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.1.2046/forge-1.10.2-12.18.1.2046-changelog.txt)

**Comment by maruohon** [comment]
This assumption of isRemote == false -> WorldServer seems to be common and also usually a reasonable one. Thus there isn't really a point in fixing this in MCMultiPart, it would still keep crashing with many other mods...

I have fixed this in my dev version of Placement Preview by piling up tons of new hacky code to get my fake world to be a WorldServer... I just need to do more testing to try to convince myself that it doesn't break other things even more massively...

All in all I quite badly regret ever releasing the Placement Preview mod due to how hacky it gets to even try to keep it working with other mods that do more advanced things on block placement >_>

**Comment by amadornes** [comment]
I was about to say, most mods don't check this because networking assumes the world is either a WorldClient or a WorldServer and it's never supposed to just be a World, and MCMP is no exception. It'd crash anyways with a ton of other mods because it's not the way MC's networking is designed to work so yes, I agree that (although it's hacky) you should make your world a WorldServer :P
