### ISSUE TITLE
crash when exit nether/aroma mining world

### ISSUE THREAD

**Issue by AndreiTS** [amadornes/MCMultiPart#71]
http://pastebin.com/U7mLp2Gz

**Comment by Camrais** [comment]
Yes that referenced post above there is mine. I really would appreciate if you would update 1.10.2 again.

Greetz
Camrais

**Comment by siccaxe** [comment]
Just want to chime in here and note that I had a similar issue. I can provide logs or perform testing if needed. Great mod! 

https://github.com/aidancbrady/Mekanism/issues/4385

**Comment by bernds** [comment]
This has bitten me as well - makes it hard to use Mekanism fully.

**Comment by siccaxe** [comment]
@bernds it's only happened to me the one time. Does it happen continually with you?

**Comment by bernds** [comment]
@siccaxe happened twice so far - the first time with some universal cables I had, the second time my pressurized tubes disappeared and i figured there's a pattern here. Now I refrain from building more infrastructure and take down the eight tubes or so I have before going into the Nether.

**Comment by Camrais** [comment]
Well as i read out through my log it said that all cable are causing the problem and therefore i was expecting that other pipes/transporter and so on from mekanism are causing this problem. So i already disabled those so my friends don't use them and i need to erase them off of the world again. Problem is that im running it on a server and when you cant even connect into the game because it instantly crashes then ye... I really hope that it will get fixed soon, since the author said that he'd only develop further on 1.10.2 if something major comes up.

**Comment by amadornes** [comment]
The problem with this is that it's been happening from the start, and I still haven't managed to figure out what's causing it, nor have any of the other people I've asked... :/

I can make a dirty patch for it, yes, I just have to check if an object is null, but I don't quite know what's causing it, which really bugs me... Same thing with the "could not find this property in this state" crash... because the property is clearly there...

If I figure out the other one within a week or so, I'll push a fix for both. If not, expect a fix for this by the end of next week (I have to study for exams and they'll be over next Friday).

**Comment by robynetzan** [comment]
Any updates on this?

**Comment by AndreiTS** [comment]
I did not have any more crashes. Using McMultipart 1.4.0, Mekanism .301

**Comment by fcpwiz** [comment]
Yeah, I'd love to know when you're pushing a new version @amadornes. Any updates on this?

**Comment by dblsaiko** [comment]
Closing because this is an MCMP1 issue which has been outdated for a while. If this issue still occurs in MCMP2 (1.11+), please open a new issue.
