### ISSUE TITLE
[MCMP2] Item with Stack Wrapper prioritizes placing over block's onActivated() method

### ISSUE THREAD

**Issue by dblsaiko** [amadornes/MCMultiPart#73]
Even if you don't hold sneak, it places the multipart before calling onActivated on the block you've clicked on. (Related to #72)

**Comment by amadornes** [comment]
I don't think that's possible since MCMP uses `PlayerInteractEvent.RightClickBlock` and that gets fired before the block gets the event. If you can find a way to do it that doesn't involve ASM, I may look into implementing it (as long as it's a sensible option and not something like calling the block's `onActivated()` method from the event handler, because that's just asking for trouble).  
You also have the option of making a PR to Forge with a new event that's fired after the player controller calls `onActivated()` and provides the value it returned to check if it's been activated or not. That could work.

**Comment by amadornes** [comment]
Closing since it was fixed with #126
