### ISSUE TITLE
Mekanism Energy Conduit Client Crash 1.10.2

### ISSUE THREAD

**Issue by SparkyBearBomb** [amadornes/MCMultiPart#89]
Originally posted to Mekanism thread: https://github.com/aidancbrady/Mekanism/issues/4631#event-1206409555

issue description:

1.10.2 Client crashes when mining up basic energy conduit
Steps to reproduce:

    place basic universal conduit
    mine it up
    crash

Version (make sure you are on the latest version before reporting):

**Forge: 1.10.2
**Mekanism: Latest 9.2.3.97
**Running this pack https://www.technicpack.net/modpack/the-1102-modpack-pack.1070627
If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://openeye.openmods.info/crashes/ec10b14166d0db658533222e4de505ce

**Comment by dblsaiko** [comment]
Closing because this is an MCMP1 issue which has been outdated for a while. If this issue still occurs in MCMP2 (1.11+), please open a new issue.

**Comment by bonnedav** [comment]
Please support 1.10.2 a lot of people are still on it for mods an packs. You are just as rude as the author of Refined Storage. I have this problem too.

**Comment by bonnedav** [comment]
You are a library. Library's should support all active versions of the game. 1.10.2 is more active then 1.11.2.

**Comment by dblsaiko** [comment]
MCMultiPart 2 is a full rewrite of the original mod, which hasn't been worked on **for 1 year**. Ama and I don't have the time or energy to work on a codebase that's been superseded just so a handful of people can play on what is essentially an EOL'd version of the game, especially right now since we're working on getting our new mod finished up to be released with a strict deadline which is already taking up a lot of our time. 1.0.0 had a lot of problems with it's design that have been fixed with the rewrite, so I think it's reasonable to leave behind the old version.

Also, no one but you is being rude in this case. Mod developers work for free because they want to. You are not entitled to updates of any kind - not for an old version, but also not for a new one. If a mod dev decides to quit or abandon a project, players have no right to say "No. You're staying here and updating it". You're most likely playing on an old version because a mod you like didn't get update, and I'm pretty sure you didn't go to the author of that mod and tell them they were rude for not updating. The license allows for it, so if you really want this fixed, fork the repo, fix it, and build a jar.

**Comment by bonnedav** [comment]
I'm sorry. I understand now. I was tired and cranky. Thank you for actually responding.
